extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/core/*.bril'
timeout = 10
[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.traced]
pipeline = [
    "bril2json",
    "brili -t {args}",
    "brili -p {args}",
]
