extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/core/*.bril'
timeout = 10
[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.traced]
pipeline = [
    "bril2json",
    "brili -t {args}",
    "brili -p {args}",
]

[runs.tracedAndLVN]
pipeline = [
    "bril2json",
    "brili -t {args}",
    "python3 ../examples/lvn.py",
    "python3 ../examples/tdce.py",
    "brili -p {args}",
]


